"""
Tests for the MiniBook package.
"""

import os

from minibook.main import generate_html, generate_mkdocs_project


def test_generate_html(resource_dir):
    """Test generating HTML with Jinja2."""
    # Define test data
    title = "Test Links"
    description = "This is a test page created by MiniBook"
    links = [
        ("Python", "https://www.python.org"),
        ("GitHub", "https://www.github.com"),
        ("Wikipedia", "https://www.wikipedia.org")
    ]
    timestamp = "2023-06-18 12:00:00"
    output_file = resource_dir / "test_output.html"

    # Generate the HTML
    result = generate_html(
        title=title,
        links=links,
        description=description,
        timestamp=timestamp,
        output_file=str(output_file)
    )

    # Check that the file was created
    assert os.path.exists(result)

    # Read the file and check its contents
    with open(result) as f:
        content = f.read()

    # Check that the title, description, and links are in the content
    assert title in content
    assert description in content
    assert "https://www.python.org" in content
    assert "https://www.github.com" in content
    assert "https://www.wikipedia.org" in content
    assert timestamp in content


def test_generate_mkdocs_project(resource_dir):
    """Test generating a MkDocs project."""
    # Define test data
    title = "Test Links"
    description = "This is a test page created by MiniBook"
    links = [
        ("Python", "https://www.python.org"),
        ("GitHub", "https://www.github.com"),
        ("Wikipedia", "https://www.wikipedia.org")
    ]
    timestamp = "2023-06-18 12:00:00"
    output_dir = resource_dir / "test_mkdocs_site"

    # Generate the MkDocs project
    result = generate_mkdocs_project(
        title=title,
        links=links,
        description=description,
        timestamp=timestamp,
        output_dir=str(output_dir)
    )

    # Check that the directory was created
    assert os.path.exists(result)

    # Check that the docs directory was created
    docs_dir = os.path.join(result, "docs")
    assert os.path.exists(docs_dir)

    # Check that the index.md file was created
    index_file = os.path.join(docs_dir, "index.md")
    assert os.path.exists(index_file)

    # Check that the mkdocs.yml file was created
    mkdocs_file = os.path.join(result, "mkdocs.yml")
    assert os.path.exists(mkdocs_file)

    # Read the index.md file and check its contents
    with open(index_file) as f:
        content = f.read()

    # Check that the title, description, and links are in the content
    assert f"# {title}" in content
    assert f"*{description}*" in content
    assert "* [Python](https://www.python.org)" in content
    assert "* [GitHub](https://www.github.com)" in content
    assert "* [Wikipedia](https://www.wikipedia.org)" in content
    assert f"*Generated by MiniBook on {timestamp}*" in content


def test_command_line_execution(resource_dir, tmp_path):
    """Test command-line execution of MiniBook."""
    import subprocess

    # Test HTML generation
    html_output = tmp_path / "test_output.html"
    html_cmd = [
        #str(run_script),
        "uv", "run", "minibook",
        "--title", "Test Links",
        "--description", "This is a test page created by MiniBook",
        "--output", str(html_output),
        "--format", "html",
        "--links",
        "python;https://www.python.org",
        #"--links github;https://www.github.com",
        #"--links wikipedia;https://www.wikipedia.org"
    ]

    html_result = subprocess.run(html_cmd, capture_output=True, text=True)

    # Check that the command executed successfully
    assert html_result.returncode == 0, f"HTML command failed with error: {html_result.stderr}"

    # Check that the HTML file was created
    assert os.path.exists(html_output)

    # Test MkDocs generation
    mkdocs_output = tmp_path / "test_mkdocs_site"
    mkdocs_cmd = [
        "uv", "run", "minibook",
        "--title", "Test Links",
        "--description", "This is a test page created by MiniBook",
        "--output", str(mkdocs_output),
        "--format", "mkdocs",
        "--links", "python;https://www.python.org",
        #"--links github;https://www.github.com",
        #"--links wikipedia;https://www.wikipedia.org"
    ]

    mkdocs_result = subprocess.run(mkdocs_cmd, capture_output=True, text=True)

    # Check that the command executed successfully
    assert mkdocs_result.returncode == 0, f"MkDocs command failed with error: {mkdocs_result.stderr}"

    # Check that the MkDocs directory was created
    assert os.path.exists(mkdocs_output)

    # Check that the docs directory was created
    docs_dir = mkdocs_output / "docs"
    assert os.path.exists(docs_dir)

    # Check that the index.md file was created
    index_file = docs_dir / "index.md"
    assert os.path.exists(index_file)

    # Check that the mkdocs.yml file was created
    mkdocs_file = mkdocs_output / "mkdocs.yml"
    assert os.path.exists(mkdocs_file)


def test_compile_command_execution(tmp_path):
    """Test command-line execution of MiniBook using the uvx command."""
    import subprocess

    # Test HTML generation
    html_output = tmp_path / "uvx_test_output.html"
    html_cmd = [
        "minibook",
        "--title", "Test Links",
        "--description", "This is a test page created by MiniBook",
        "--output", str(html_output),
        "--format", "html",
        "--links",
        "python;https://www.python.org",
    ]

    html_result = subprocess.run(html_cmd, capture_output=True, text=True)

    # Check that the command executed successfully
    assert html_result.returncode == 0, f"HTML command failed with error: {html_result.stderr}"

    # Check that the HTML file was created
    assert os.path.exists(html_output)

    # Test MkDocs generation
    mkdocs_output = tmp_path / "uvx_test_mkdocs_site"
    mkdocs_cmd = [
        "minibook",
        "--title", "Test Links",
        "--description", "This is a test page created by MiniBook",
        "--output", str(mkdocs_output),
        "--format", "mkdocs",
        "--links", "python;https://www.python.org",
    ]

    mkdocs_result = subprocess.run(mkdocs_cmd, capture_output=True, text=True)

    # Check that the command executed successfully
    assert mkdocs_result.returncode == 0, f"MkDocs command failed with error: {mkdocs_result.stderr}"

    # Check that the MkDocs directory was created
    assert os.path.exists(mkdocs_output)

    # Check that the docs directory was created
    docs_dir = mkdocs_output / "docs"
    assert os.path.exists(docs_dir)

    # Check that the index.md file was created
    index_file = docs_dir / "index.md"
    assert os.path.exists(index_file)

    # Check that the mkdocs.yml file was created
    mkdocs_file = mkdocs_output / "mkdocs.yml"
    assert os.path.exists(mkdocs_file)


def test_no_links_provided():
    """Test command-line execution of MiniBook when no links are provided."""
    import subprocess

    # Test with no links parameter
    cmd = [
        "minibook",
        "--title", "Test Links",
        "--description", "This is a test page created by MiniBook",
        "--format", "html",
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    # Check that the command failed with the expected error message
    assert result.returncode == 1, "Command should fail when no links are provided"
    assert "No links provided. Exiting." in result.stderr


def test_multiline_links(tmp_path):
    """Test command-line execution of MiniBook with multi-line links."""
    import subprocess

    # Test HTML generation with multi-line links
    html_output = tmp_path / "multiline_test_output.html"

    # Create a multi-line string with different formats
    multiline_links = "Python;https://www.python.org\nGitHub;https://www.github.com"
    escaped_links = "Wikipedia;https://www.wikipedia.org\\nMiniBook;https://github.com/tschm/minibook"

    # Test with actual newlines
    html_cmd_newlines = [
        "minibook",
        "--title", "Multi-line Links Test",
        "--description", "Testing multi-line links",
        "--output", str(html_output),
        "--format", "html",
        "--links", multiline_links,
    ]

    html_result_newlines = subprocess.run(html_cmd_newlines, capture_output=True, text=True)

    # Check that the command executed successfully
    assert html_result_newlines.returncode == 0, f"HTML command with newlines failed with error: {html_result_newlines.stderr}"

    # Check that the HTML file was created
    assert os.path.exists(html_output)

    # Read the file and check its contents
    with open(html_output) as f:
        content = f.read()

    # Check that all links are in the content
    assert "https://www.python.org" in content
    assert "https://www.github.com" in content

    # Test with escaped newlines
    html_output_escaped = tmp_path / "escaped_test_output.html"
    html_cmd_escaped = [
        "minibook",
        "--title", "Escaped Newlines Test",
        "--description", "Testing escaped newlines in links",
        "--output", str(html_output_escaped),
        "--format", "html",
        "--links", escaped_links,
    ]

    html_result_escaped = subprocess.run(html_cmd_escaped, capture_output=True, text=True)

    # Check that the command executed successfully
    assert html_result_escaped.returncode == 0, f"HTML command with escaped newlines failed with error: {html_result_escaped.stderr}"

    # Check that the HTML file was created
    assert os.path.exists(html_output_escaped)

    # Read the file and check its contents
    with open(html_output_escaped) as f:
        content = f.read()

    # Check that all links are in the content
    assert "https://www.wikipedia.org" in content
    assert "https://github.com/tschm/minibook" in content
