name: 'Book Action'
description: 'Create a Book from a list of links'
inputs:
  title:
    description: 'Title of the minibook'
    required: false
    default: 'My Links'
  subtitle:
    description: 'Description of the minibook'
    required: false
    default: ''
  links:
    description: 'JSON formatted links: can be a list of objects with name/url keys,
    a list of arrays, or a dictionary'
    required: true
  template:
    description: 'Path to a custom Jinja2 template file for HTML output'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.12
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.12

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    # Step 2: Make the minibook
    - name: Create minibook
      shell: bash
      run: |
        uvx minibook@v0.0.11 \
          --title "${{ inputs.title }}" \
          --description "${{ inputs.subtitle }}" \
          --output 'artifacts' \
          --links '${{ inputs.links }}' \
          --template '${{ inputs.template }}'

    - name: Inspect artifacts
      shell: bash
      run: |
        tree artifacts

    # Package all artifacts for GitHub Pages deployment
    # This prepares the combined outputs for deployment
    - name: Upload static files as artifact
      id: upload
      uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
      with:
        path: artifacts/  # Path to the directory containing all artifacts

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
