name: 'Minibook Action'
description: 'Create a minibook from a list of links'
inputs:
  title:
    description: 'Title of the minibook'
    required: false
    default: 'My Links'
  description:
    description: 'Description of the minibook'
    required: false
    default: ''
  output:
    description: 'Output directory'
    required: true
  links:
    description: 'JSON formatted links: can be a list of objects with name/url keys,
    a list of arrays, or a dictionary'
    required: true
  format:
    description: 'Output format: html or mkdocs'
    required: false
    default: 'html'
  timestamp:
    description: 'Fixed timestamp for testing purposes'
    required: false
    default: ''
  template:
    description: 'Path to a custom Jinja2 template file for HTML output'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # Download all artifacts from previous jobs
    # This collects the outputs from both the jupyter and marimo jobs
    #- name: Download all artifacts
    #  uses: actions/download-artifact@v4
    #  with:
    #    path: ${{ inputs.output }}

    - name: Set up Python 3.12
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.12

    - name: Create minibook
      shell: bash
      run: |
        TIMESTAMP_ARG=""
        if [ -n "${{ inputs.timestamp }}" ]; then
          TIMESTAMP_ARG="--timestamp ${{ inputs.timestamp }}"
        fi

        TEMPLATE_ARG=""
        if [ -n "${{ inputs.template }}" ]; then
          TEMPLATE_ARG="--template ${{ inputs.template }}"
        fi

        uvx minibook \
          --title "${{ inputs.title }}" \
          --description "${{ inputs.description }}" \
          --output "${{ inputs.output }}" \
          --format "${{ inputs.format }}" \
          --links '${{ inputs.links }}' \
          $TIMESTAMP_ARG \
          $TEMPLATE_ARG
