name: 'Minibook Action'
description: 'Create a minibook from a list of links'
inputs:
  title:
    description: 'Title of the minibook'
    required: false
    default: 'My Links'
  description:
    description: 'Description of the minibook'
    required: false
    default: ''
  output:
    description: 'Output file or directory'
    required: false
    default: 'minibook.html'
  links:
    description: 'JSON formatted links: can be a list of objects with name/url keys,
    a list of arrays, or a dictionary'
    required: true
  format:
    description: 'Output format: html or mkdocs'
    required: false
    default: 'html'
  timestamp:
    description: 'Fixed timestamp for testing purposes'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install minibook

    - name: Create minibook
      shell: bash
      run: |
        LINKS="${{ inputs.links }}"
        TIMESTAMP_ARG=""
        if [ -n "${{ inputs.timestamp }}" ]; then
          TIMESTAMP_ARG="--timestamp ${{ inputs.timestamp }}"
        fi

        minibook \
          --title "${{ inputs.title }}" \
          --description "${{ inputs.description }}" \
          --output "${{ inputs.output }}" \
          --format "${{ inputs.format }}" \
          --links "$LINKS" \
          $TIMESTAMP_ARG
