name: "Test Minibook Action"

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    paths:
      - '.github/actions/minibook/**'  # Run when the action is modified

jobs:
  test-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create HTML Minibook
        uses: ./.github/actions/minibook
        with:
          title: "Test HTML Minibook"
          description: "This is a test HTML minibook created by the Minibook Action"
          output: "test-html-minibook.html"
          format: "html"
          links: "GitHub;https://github.com,Python;https://python.org,Minibook;https://github.com/tschm/minibook"

      - name: Upload HTML Minibook
        uses: actions/upload-artifact@v4
        with:
          name: html-minibook
          path: test-html-minibook.html

  test-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create MkDocs Minibook
        uses: ./.github/actions/minibook
        with:
          title: "Test MkDocs Minibook"
          description: "This is a test MkDocs minibook created by the Minibook Action"
          output: "test-mkdocs-minibook"
          format: "mkdocs"
          links: "GitHub;https://github.com,Python;https://python.org,Minibook;https://github.com/tschm/minibook"

      - name: Upload MkDocs Minibook
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-minibook
          path: test-mkdocs-minibook
